### ISSUE TITLE
Android: Undefined is not a function

### ISSUE THREAD

**Issue by qasim90** [hansemannn/titanium-firebase-auth#3]
It seems no method is available in android module. I got the above error on `FireAuth.signInWithEmail({...` and `FireAuth.signInAnonymously{` 
Tried to log both methods on console
`console.log('FireAuth: ',FireAuth.signInWithEmail,typeof FireAuth.signInWithEmail);`
and got
`[INFO] :   FireAuth:  undefined undefined`

**Comment by qasim90** [comment]
I think you are referring to the typo in readme as it seems fine in the source code. PR #4 submitted

**Comment by hansemannn** [comment]
Fixed in latest master.
