### ISSUE TITLE
Run with Android 

### ISSUE THREAD

**Issue by amo222lpatil** [hansemannn/titanium-firebase-auth#5]
[ERROR] :  TiExceptionHandler: (main) [0,130] - Message: Uncaught Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.firebase.auth.FirebaseAuth.signInWithEmailAndPassword(java.lang.String, java.lang.String)' on a null object reference
[ERROR] :  TiExceptionHandler: (main) [0,130] - Source: 	FirebaseAuth.signInWithEmail({
[ERROR] :  V8Exception: Exception occurred at /alloy/controllers/index.js:81: Uncaught Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.firebase.auth.FirebaseAuth.signInWithEmailAndPassword(java.lang.String, java.lang.String)' on a null object reference
[ERROR] :  V8Exception: Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.firebase.auth.FirebaseAuth.signInWithEmailAndPassword(java.lang.String, java.lang.String)' on a null object reference

**Comment by hansemannn** [comment]
Missing environment, example code and any other notes. This is not how issues work, sorry.

**Comment by amo222lpatil** [comment]
Sorry for that. I created new issue with description.
